In [1]:
import array
from array import*
import numpy as np

In [2]:
import array
arr1=array.array('i',[1,2,3,4,5])  # array.array means (module name.class name)
arr1

array('i', [1, 2, 3, 4, 5])

In [3]:
for i in arr1:
    print(i)

1
2
3
4
5


In [4]:
[x if x is not None else '' for x in arr1]

[1, 2, 3, 4, 5]

In [5]:
[x if x%2==0 else 'odd' for x in arr1]

['odd', 2, 'odd', 4, 'odd']

In [6]:
print(arr1[0])

1


In [7]:
(arr1)

array('i', [1, 2, 3, 4, 5])

In [8]:
from array import*
arr2=array('i',[1,2,3,45])
arr2

array('i', [1, 2, 3, 45])

In [9]:
print(arr2[2])

3


In [11]:
# 1-D
stu_roll=array('i',[])
# n=int(input('enter the lenght of array : ')
for i in range(int(input('enter the lenght of array : '))):
      stu_roll.append(int(input('enter the enlement of array : ')))
for i in range(len(stu_roll)):
      print(i,'--->',stu_roll[i])

enter the lenght of array : 1
enter the enlement of array : 4
0 ---> 4


In [12]:
str2='amarendra kumar '

In [13]:
str2.split('n')

['amare', 'dra kumar ']

In [14]:
import numpy as np 
d=np.zeros((2,3,2),dtype='int')
d

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [15]:
str2

'amarendra kumar '

In [16]:
fre={}
for i in str2.split():
    if i in fre:
        fre[i]+=1
    else:
        fre[i]=1
print(fre)

{'amarendra': 1, 'kumar': 1}


In [17]:
from collections import Counter
str3='Narendra Damodardas Modi is an Indian politician who has served as the 14th Prime Minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament for Varanasi.'
counter=dict(Counter(str3.split()))
counter

{'Narendra': 1,
 'Damodardas': 1,
 'Modi': 2,
 'is': 2,
 'an': 1,
 'Indian': 1,
 'politician': 1,
 'who': 1,
 'has': 1,
 'served': 1,
 'as': 1,
 'the': 3,
 '14th': 1,
 'Prime': 1,
 'Minister': 2,
 'of': 3,
 'India': 1,
 'since': 1,
 'May': 1,
 '2014.': 1,
 'was': 1,
 'Chief': 1,
 'Gujarat': 1,
 'from': 1,
 '2001': 1,
 'to': 1,
 '2014': 1,
 'and': 1,
 'Member': 1,
 'Parliament': 1,
 'for': 1,
 'Varanasi.': 1}

In [18]:
max_counts=max(counter.values())
[num for num,count in counter.items() if max_counts==count]

['the', 'of']

In [19]:
max(counter,key=counter.get)

'the'

In [20]:
str2='amarendra kumar kushwaha'
dct={}
for i in str2:
    if i in dct:
        dct[i]+=1
    else:
        dct[i]=1
print(dct)
max_values=max(dct.values())
[key for key ,value in dct.items() if max_values==value]

{'a': 6, 'm': 2, 'r': 3, 'e': 1, 'n': 1, 'd': 1, ' ': 2, 'k': 2, 'u': 2, 's': 1, 'h': 2, 'w': 1}


['a']

In [21]:
result=max(dct,key=dct.get)
result

'a'

In [22]:
result=min(dct,key=dct.get)
result

'e'

In [23]:
array=np.arange(12).reshape(3,4)

In [24]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.argmax(array)

11

In [26]:
np.argmax(array,axis=1)

array([3, 3, 3], dtype=int64)

In [27]:
arr1=array.flatten()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
str1='my name is amarendra kumar kushwaha'
dct=dict(Counter(str1))
dct

{'m': 4,
 'y': 1,
 ' ': 5,
 'n': 2,
 'a': 7,
 'e': 2,
 'i': 1,
 's': 2,
 'r': 3,
 'd': 1,
 'k': 2,
 'u': 2,
 'h': 2,
 'w': 1}