#  Add Two Numbers With User Input

In [1]:
# Store input numbers
num1 = input('Enter first number: ')
num2 = input('Enter second number: ')

# Add two numbers
sum = float(num1) + float(num2)

# Display the sum
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

Enter first number: 4
Enter second number: 5
The sum of 4 and 5 is 9.0


In [2]:
print(f'The sum of {num1} and {num2} is {sum}')

The sum of 4 and 5 is 9.0


In [4]:
def addition(num1,num2):
    num1=int(input("enter the first number : "))
    num2=int(input("enter the second number: "))
    sum1=float(num1)+float(num2)
    return sum1
addition(num1,num2)

enter the first number : 4
enter the second number: 5


9.0

# Python Program to calculate the square root

In [5]:
# Note: change this value for a different result
num = 16

# To take the input from the user
#num = float(input('Enter a number: '))

num_sqrt = num**0.5 ## values of square roots 0.5
print('The square root of %0.2f is %0.2f'%(num ,num_sqrt))

The square root of 16.00 is 4.00


# Python Program to Calculate the Area of a Triangle

In [6]:
a = 5
b = 6
c = 7

# Uncomment below to take inputs from the user
# a = float(input('Enter first side: '))
# b = float(input('Enter second side: '))
# c = float(input('Enter third side: '))

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5   #values of roots 0.5 
print('The area of the triangle is %0.2f' %area)
#print(area)

The area of the triangle is 14.70


# Python Program to Solve Quadratic Equation

In [7]:
# Solve the quadratic equation ax**2 + bx + c = 0

# import complex math module
import cmath

a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-3+0j) and (-2+0j)


# Python Program to Swap Two Variables

In [8]:
x=5
y=10
x,y=y,x
x,y

(10, 5)

In [9]:
x = 5
y = 10

# To take inputs from the user
#x = input('Enter value of x: ')
#y = input('Enter value of y: ')

print('The value of x before swapping: {}'.format(x))
print('The value of y before swapping: {}'.format(y))
print()
# create a temporary variable and swap the values
temp=x
x=y
y=temp

print('The value of x after swapping: {}'.format(x))
print('The value of y after swapping: {}'.format(y))

The value of x before swapping: 5
The value of y before swapping: 10

The value of x after swapping: 10
The value of y after swapping: 5


# Python Program to Generate a Random Number

In [10]:
# importing the random module
import random
import numpy as np

print(random.randint(0,9))

8


In [11]:
x=np.random.rand(4) # uniform distributions
x

array([0.19368993, 0.516317  , 0.66476076, 0.19580434])

In [12]:
np.max(x)

0.6647607583415818

In [13]:
np.random.randn(4) # normal distributions

array([-1.5266848 , -0.475092  ,  0.79398501,  0.19403446])

# Python Program to Convert Kilometers to Miles

In [14]:
# Taking kilometers input from the user
kilometers = float(input("Enter value in kilometers: "))

# conversion factor
conv_fac = 0.621371

# calculate miles
miles = kilometers * conv_fac
print('%0.2f kilometers is equal to %0.2f miles' %(kilometers,miles))

Enter value in kilometers: 


ValueError: could not convert string to float: ''

# Python Program to Convert Celsius To Fahrenheit

In [15]:
# Python Program to convert temperature in celsius to fahrenheit

# change this value for a different result
celsius = 37.5

# calculate fahrenheit
fahrenheit = (celsius * 1.8) + 32
print('%0.1f degree Celsius is equal to %0.1f degree Fahrenheit' %(celsius,fahrenheit))

37.5 degree Celsius is equal to 99.5 degree Fahrenheit


# Python Program to Check if a Number is Positive, Negative or 0

In [16]:

num = float(input("Enter a number: "))
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Enter a number: 


ValueError: could not convert string to float: ''

# Python Program to Check if a Number is Odd or Even

In [17]:
# Python program to check if the input number is odd or even.
# A number is even if division by 2 gives a remainder of 0.
# If the remainder is 1, it is an odd number.

num = int(input("Enter a number: "))
if num % 2== 0:
    print('is even')
    #print("{0} is Even".format(num))
else:
    print("{0} is Odd".format(num))

Enter a number: 


ValueError: invalid literal for int() with base 10: ''

# Python Program to Check Leap Year

In [ ]:
# Python program to check if year is a leap year or not

# year = 2023

# To get year (integer input) from the user
year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year%400==0) and (year%100==0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year%4==0) and (year%100!=0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

In [17]:
year=int(input('enter the year: '))
if (year%400==0)&(year%100==0):
    print('leap year')
elif (year%4==0)&(year%100!=0):
    print('leap Year')
else:
    print('not leap year')

enter the year: 


ValueError: invalid literal for int() with base 10: ''

In [18]:
year=int(input('Enter the years : '))
# if(year%400==0)and(year%100==0):
#     print("{0} is a leap year".format(year))
if(year%4==0)and(year%100!=0):
    print("{0} is a leap year".format(year))
else:
    print("{0} is not leap year".format(year))

Enter the years : 


ValueError: invalid literal for int() with base 10: ''

# Python Program to Find the Largest Among Three Numbers

In [19]:
# Python program to find the largest number among the three input numbers

# change the values of num1, num2 and num3
# for a different result
num1 = 10
num2 = 14
num3 = 12

# uncomment following lines to take three numbers from user
#num1 = float(input("Enter first number: "))
#num2 = float(input("Enter second number: "))
#num3 = float(input("Enter third number: "))

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is", largest)

The largest number is 14


# Python Program to Print all Prime Numbers in an Interval

In [20]:
# Python program to display all the prime numbers within an interval

lower = 10
upper = 20

print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper + 1):
   # all prime numbers are greater than 1
   if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                break
            else:
                print(num,end=' ')

Prime numbers between 10 and 20 are:
11 11 11 11 11 11 11 11 11 13 13 13 13 13 13 13 13 13 13 13 15 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 

In [21]:
print('amar'+ 'erfgb')

amarerfgb


In [22]:
for i in range(20):
    if i>1:
        print(i,end=' ')

2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

# Multiplication table (from 1 to 10) in Python

In [23]:
# Multiplication table (from 1 to 10) in Python

num = 12

# To take input from the user
# num = int(input("Display multiplication table of? "))

# Iterate 10 times from i = 1 to 10
for i in range(1, 11):
    print(num, '*', i, '=', num*i)

12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120


In [24]:
[x*12 for x in range(1,11)]

[12, 24, 36, 48, 60, 72, 84, 96, 108, 120]

# Python Program to Print the Fibonacci sequence

In [25]:
# Program to display the Fibonacci sequence up to n-th term

nterms = int(input("How many terms? "))

# first two terms
n1, n2 = 0, 1
count = 0

# check if the number of terms is valid
if nterms <= 0:
    print("Please enter a positive integer")
# if there is only one term, return n1
elif nterms == 1:
    print("Fibonacci sequence upto",nterms,":")
    print(n1)
# generate fibonacci sequence
else:
    print("Fibonacci sequence:")
    while count < nterms:
        print(n1)
        nth = n1 + n2
       # update values
        n1 = n2
        n2 = nth
        count += 1

How many terms? 


ValueError: invalid literal for int() with base 10: ''

In [26]:
num=int(input("enter the number :"))
a=1
b=1
output=[]
for i in range(num):
    output.append(a)
    a,b=b,a+b
print(output)

enter the number :


ValueError: invalid literal for int() with base 10: ''

# Python Program to Check Armstrong Number

In [28]:
# Python program to check if the number is an Armstrong number or not

# take input from the user
num = int(input("Enter a number: "))

# initialize sum
sum = 0

# find the sum of the cube of each digit
temp = num
while temp > 0:
    digit = temp % 10
    sum +=digit ** 3
    temp //= 10

# display the result
if num == sum:
    print(num,"is an Armstrong number")
else:
    print(num,"is not an Armstrong number")

Enter a number: 153
153 is an Armstrong number


In [29]:
num=int(input('enter the num : '))
sum=0
temp=num
while temp>0:
    digit=temp%10
    sum+=digit**3
    temp//=10
if num==sum:
    print(num,'is an Armstrong number')
else:
    print(num,'is not an Armstrong number')

enter the num : 153
153 is an Armstrong number


In [30]:
def pali(str1):
    return str1
str1='mom'
str3=str1[::-1]
if str1==str3:
    print('yes')
else:
    print('no')

yes


In [31]:
def pali(str1):
    return str1==str1[::-1]
str1='mom'
if str1:
    print('Yes')
else:
    print('no')

Yes


In [32]:
str3

'mom'

In [33]:
def fact(num):
    if (num==0 or num==1):
        return 1
    else:
        return num*fact(num-1)
fact(5)

120

In [34]:
m=int(input('enter the numbers: '))
sum1=0
n=m
while m>0:
    digits=m%10
    sum1=sum1+digits**3
    m=m//10
print(sum1)
# if n==sum:
#     print(n,'its armstrong numbers : ')
# else:
#     print(n,'its not armstrongs numbers :')

enter the numbers: 125
134


In [35]:
123//10

12

# inverse numbers

In [36]:
num=123
sum=0
while num>0:
    #n=num%10
    sum=sum*10+num%10
    num=num//10
print(sum)

321


In [37]:
11%10

1

In [38]:
12//10

1

In [39]:
str1='0123'
for i in str1[::-1]:
    print(int(i),end='')
#     x=i
#     print(''.join(i),end='')

3210

In [40]:
int(''.join(reversed(str1)))

3210

In [41]:
num1=123
sum=0
while num1>0:
    n=num1%10
    sum=sum*10+n
    num1=num1//10
print(sum)

321


In [46]:
n=1234
print(int(str(n)[::-1]))

4321


In [47]:
def is_df(str1):
    return str1
str1=input('enter the string : ')
new_str1=str1[::-1]
if str1==new_str1:
    print('yes')
else:
    print('no')

enter the string : 4
yes


# Python Program to Find Numbers Divisible by Another Number

In [48]:
my_list=[123,543,987,2345,65,52,1340,130]
result=list(filter(lambda x: x%13==0, my_list))
print('Numbers are divisible by 13 : ',result)

Numbers are divisible by 13 :  [65, 52, 130]


# Python Program to Convert Decimal to Binary, Octal and Hexadecimal

In [49]:
# Python program to convert decimal into other number systems
dec = 344

print("The decimal value of", dec, "is:")
print(bin(dec), "in binary.")
print(oct(dec), "in octal.")
print(hex(dec), "in hexadecimal.")

The decimal value of 344 is:
0b101011000 in binary.
0o530 in octal.
0x158 in hexadecimal.


# Python Program to Display Powers of 2 Using Anonymous Function

In [50]:
terms=int(input('how many terms '))
result=list(map(lambda x: 2**x,range(terms)))

for i in range(terms):
    print('2 raised to the power',i,'is',result[i])

how many terms 5
2 raised to the power 0 is 1
2 raised to the power 1 is 2
2 raised to the power 2 is 4
2 raised to the power 3 is 8
2 raised to the power 4 is 16


# Python program to find H.C.F of two numbers

In [51]:
# Python program to find H.C.F of two numbers

# define a function
def compute_hcf(x, y):

# choose the smaller number
    if x > y:
        smaller = y
    else:
        smaller = x
    for i in range(1, smaller+1):
        if((x % i == 0) and (y % i == 0)):
            hcf = i 
    return hcf

num1 = 54 
num2 = 24

print("The H.C.F. is", compute_hcf(num1, num2))

The H.C.F. is 6


# Python Program to find the L.C.M. of two input number

In [52]:
# Python Program to find the L.C.M. of two input number

def compute_lcm(x, y):

   # choose the greater number
    if x > y:
        greater = x
    else:
        greater = y
    while(True):
        if((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm

num1 = 54
num2 = 24

print("The L.C.M. is", compute_lcm(num1, num2))

The L.C.M. is 216


# Python Program to find the factors of a number

In [54]:
# Python Program to find the factors of a number

# This function computes the factor of the argument passed
def print_factors(x):
    print("The factors of",x,"are:")
    for i in range(1, x+1):
        if x % i == 0:
            print(i)
num =10
print_factors(num)

The factors of 10 are:
1
2
5
10


In [55]:
def factor(x):
    for i in range(1,x+1):
        if x%i==0:
            print(i)
num=10
factor(num)

1
2
5
10


In [56]:
def its_prime(num):
    for i in range(2,num):
        if num%2==0:
            print('oho! its not prime number ')
            break
        else:
            print('yes! its prime numbers')
            break
num=int(input('enter the numbers: '))
its_prime(num)

enter the numbers: 4
oho! its not prime number 


# Python Program to Make a Simple Calculator

In [57]:
# This function adds two numbers
def add(x, y):
    return x + y

# This function subtracts two numbers
def subtract(x, y):
    return x - y

# This function multiplies two numbers
def multiply(x, y):
    return x * y

# This function divides two numbers
def divide(x, y):
    return x / y


print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

while True:
    # take input from the user
    choice = input("Enter choice(1/2/3/4): ")

    # check if choice is one of the four options
    if choice in ('1', '2', '3', '4'):
        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input. Please enter a number.")
            continue

        if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))
        
        # check if user wants another calculation
        # break the while loop if answer is no
        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation == "no":
            break
    else:
        print("Invalid Input")

Select operation.
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice(1/2/3/4): 4
Enter first number: 65
Enter second number: 65
65.0 / 65.0 = 1.0
Let's do next calculation? (yes/no): yes
Enter choice(1/2/3/4): 1
Enter first number: 5
Enter second number: 5
5.0 + 5.0 = 10.0
Let's do next calculation? (yes/no): no


In [58]:
import pandas as pd
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})
result=df.loc[0,'A']+df.iloc[0,1]
result

5

# Python program to shuffle a deck of card

In [59]:
# Python program to shuffle a deck of card

# importing modules
import itertools, random

# make a deck of cards
deck = list(itertools.product(range(1,14),['Spade','Heart','Diamond','Club']))

# shuffle the cards
random.shuffle(deck)

# draw five cards
print("You got:")
for i in range(5):
    print(deck[i][0], "of", deck[i][1])

You got:
6 of Club
13 of Spade
9 of Club
4 of Heart
8 of Spade


# Program to add two matrices using nested loop

In [60]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[i])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [61]:
import numpy as np
a=np.matrix('1,2,3;4,5,6;7,8,9')
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
b=np.matrix('4,34,3;8,5,34;8,1,10')
b

matrix([[ 4, 34,  3],
        [ 8,  5, 34],
        [ 8,  1, 10]])

In [63]:
c=a+b
c

matrix([[ 5, 36,  6],
        [12, 10, 40],
        [15,  9, 19]])

In [64]:
d=a*b
d

matrix([[ 44,  47, 101],
        [104, 167, 242],
        [164, 287, 383]])

In [65]:
w=a-b
w

matrix([[ -3, -32,   0],
        [ -4,   0, -28],
        [ -1,   7,  -1]])

In [66]:
import numpy as np
result1=np.zeros([3,3],dtype='int')
for i in range(len(X)):
    for j in range(len(X[i])):
         result1[i][j]=X[i][j]+Y[i][j]
for i in result1:
    print(i)

[17 15  4]
[10 12  9]
[11 13 18]


In [67]:
import numpy as np
np.zeros([3,3],dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
a=[1,2,3,4,5,6]
b=[3,4,5,6]
result=[]
for i,j in zip(a,b):
    result.append(i+j)
print(result)

[4, 6, 8, 10]


In [70]:
import calendar
yy=2023
mm=12
print(calendar.month(yy,mm))

   December 2023
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



In [71]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[i])):
        result[j][i] = X[i][j]

for r in result:
    print(r)

[12, 4, 3]
[7, 5, 8]


# Program to multiply two matrices using nested loops

In [72]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


# Program to check if a string is palindrome or not

In [73]:
my_str = my_str.casefold()
my_str

NameError: name 'my_str' is not defined

In [74]:
rev_str

NameError: name 'rev_str' is not defined

In [75]:
# Program to check if a string is palindrome or not

my_str = 'aIbohPhoBiA'

# make it suitable for caseless comparison
my_str = my_str.casefold()

# reverse the string
rev_str = reversed(my_str)

# check if the string is equal to its reverse
if list(my_str) == list(rev_str):
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")

The string is a palindrome.


In [76]:
my_str = 'aIbohPhoBiA'

In [84]:
my_str = my_str.casefold()
my_str

'aibohphobia'

In [85]:
rev_str = reversed(my_str)

In [86]:
reversed(my_str)

In [87]:
rev_str

In [88]:
def palindrome(str1):
    return str1
str1='Malayalam'
str1=str1.casefold()
str2=reversed(str1)
if list(str1)==list(str2):
    print('is_palindrome')
else:
    print('is_ not palindrome')

is_palindrome


In [89]:
list(str1)

['m', 'a', 'l', 'a', 'y', 'a', 'l', 'a', 'm']

In [90]:
c

matrix([[ 5, 36,  6],
        [12, 10, 40],
        [15,  9, 19]])

In [91]:
d

matrix([[ 44,  47, 101],
        [104, 167, 242],
        [164, 287, 383]])

In [95]:
result=np.zeros((3,3),dtype='int32')
result

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [104]:
for i in range(len(c)):
    for j in range(len(d[0])):
        for k in range(d):
            result[i][j]=c[i][j]+d[i][j]

TypeError: only integer scalar arrays can be converted to a scalar index